version: "3.3"

services:
  web:
    image: nodues_frontend
    container_name: nodues_frontend
    restart: always
    build:
        context: .
    ports:
      - "9345:3000"
    command: sh -c "cd /app && serve -s build"