version: "3.3"

services:
  web:
    image: test_nodues_frontend
    container_name: test_nodues_frontend
    restart: always
    build:
        context: .
    ports:
      - "9345:3000"
    networks:
      - backend_default
    command: sh -c "cd /app && serve -s build"

networks:
  backend_default:
    external: true
    
