version: '2'

services:
  web:
    image: nodues_backend
    container_name: nodues_backend
    build: 
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9346:3002"